---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.0
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.8
  run_list: ["recipe[apt]"]
- name: fedora-19
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20
- name: fedora-21
- name: opensuse-13.1
  driver_config:
    box: opscode-opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box
# FreeBSD platform requires to run kitchen verify twice by hand
# - name: freebsd-9.2
#   run_list: ["recipe[freebsd::portsnap]"]
#   driver_config:
#     box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-9.2_chef-provisionerless.box
# - name: freebsd-10.1
#   run_list: ["recipe[freebsd::portsnap]"]
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.10
  run_list: ["recipe[apt]"]

suites:
- name: latest
  run_list:
    - recipe[encrypted_attributes_test::default]
- name: chef11
  run_list:
    - recipe[encrypted_attributes_test::default]
  provisioner:
    require_chef_omnibus: 11.16.4
- name: chef11old
  run_list:
    - recipe[encrypted_attributes_test::default]
  provisioner:
    require_chef_omnibus: 11.12.8
- name: gem050
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
      version: 0.5.0
- name: gem050-chef11
  provisioner:
    require_chef_omnibus: 11.16.4
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
      version: 0.5.0
- name: gem050-chef11old
  provisioner:
    require_chef_omnibus: 11.12.8
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
      version: 0.5.0
# chef-encrypted-attributes 0.3.0 only works with Chef 11 due to depends
# - name: gem030
#   run_list:
#     - recipe[encrypted_attributes_test::default]
#   attributes:
#     encrypted_attributes:
#       version: 0.3.0
- name: gem030-chef11
  provisioner:
    require_chef_omnibus: 11.16.4
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
      version: 0.3.0
- name: gem030-chef11old
  provisioner:
    require_chef_omnibus: 11.12.8
  run_list:
    - recipe[encrypted_attributes_test::default]
  attributes:
    encrypted_attributes:
      version: 0.3.0
- name: key
  run_list:
    - recipe[encrypted_attributes_test::expose_key]
